# Generated by Django 5.2 on 2025-05-07 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField(max_length=100)),
                ('last_name', models.TextField(max_length=100)),
                ('status', models.TextField(max_length=20)),
                ('date_added', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
