# Generated by Django 5.2.3 on 2025-06-25 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('status_choices', models.CharField(choices=[('L', 'Loathed'), ('I', 'Ignored'), ('F', 'Forgiven')], default='L', max_length=1)),
            ],
        ),
    ]
